// <auto-generated />
namespace FinalKonusu2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class hastaneMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hastaneMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202505040958306_hastaneMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
